#!/usr/bin/env python3

import sys

from typing import Iterator

from query import go2locs, loc2region


def get_regions(go_id: str) -> Iterator[tuple[str, tuple[str, int, int]]]:
    locs = go2locs(go_id)
    genes = [loc2region(loc) for loc in locs]

    return zip(locs, genes)


go_id = sys.argv[1]
res = get_regions(go_id)
for loc, (region, start, end) in res:
    print(loc, region, f"{start}-{end}", sep="\t")
